version: "3.8"
services:
  zmq-server:
    build: .
    container_name: zmq-server
    command: ./server
    networks:
      zmq-network:
        ipv4_address: 192.168.1.2

  zmq-client:
    build: .
    container_name: zmq-client
    command: ./client
    networks:
      zmq-network:
        ipv4_address: 192.168.1.3

networks:
  zmq-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
